### PR TITLE
Updated PopupEdiotr_ForceResize() code

### PR DESCRIPTION
**Pull request by thekingofspain**
The code in the example did not work for me.  I have update the code the code a method that did work for me.  The source of the code if from the following reference:  https://www.outsystems.com/forums/discussion/15004/resizing-a-richwidgets-popup-at-runtime/#Post139301

### CODE REVIEW

**Comment by rmlos** [comment]
We sent this code edit to our Engineering team and they could not make it work. We're now checking the original document.

**Comment by rmlos** [comment]
The code in the original document works correctly.

**Comment by pjft** [comment]
@thekingofspain maybe the reverse question, apologies: in what scenario (browser, OS version, etc) did the code in the docs not work that this worked?

**Comment by rmlos** [comment]
Hello, @thekingofspain! Unfortunately, we couldn't make this code work. Also, the original code works. We can't do much but to:

* Suggest that you try [How to dynamically resize a pop-up window](https://success.outsystems.com/Documentation/How-to_Guides/Front-End/How_to_dynamically_resize_a_pop-up_window) again. If it doesn't work for you, send us feedback containing the OutSystems Web UI version number in the **Leave your feedback** box in the page. You can also comment here on GitHub. 
* Close this pull request, as the code did not pass code review in Engineering.

We're sorry for closing the pull request, as we appreciate contributions from all our users.

**Pull request closed without merging**
